### ISSUE TITLE
php 7.1编译有问题

### ISSUE THREAD

**Issue by sgt-dongyz** [easy-swoole/compiler#1]
/usr/local/src/compiler/src/compiler.c: In function ‘mixed_opcode’:
/usr/local/src/compiler/src/compiler.c:240:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < opline->last; i++) {
     ^
/usr/local/src/compiler/src/compiler.c:240:5: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [src/compiler.lo] Error 1

**Comment by kiss291323003** [comment]
你gcc需要升级
